name: Update Events JSON
permissions:
  contents: write
  
on:
  schedule:
    - cron: '* 24 * * *'
  workflow_dispatch:

jobs:
  update-events:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: python -m pip install pandas

      - name: Download and convert Google Sheets CSV to JSON
        run: |
          curl -L -o sheet.csv "https://docs.google.com/spreadsheets/d/e/2PACX-1vRj1ph9bBAsVVOoTruj-mYznqVPoFl8RpTK4ng5SPXBe00-N7DUrxsW3Vh_Nv0W2Xl-4PscSzpVXrzY/pub?output=csv"

            echo "import pandas as pd" > convert.py
            echo "from datetime import datetime" >> convert.py
            echo "print('Reading sheet.csv...')" >> convert.py
            echo "df = pd.read_csv('sheet.csv')" >> convert.py
            cat sheet.csv
            echo "print('Original rows:', len(df))" >> convert.py
            echo "df = df.dropna(how='all')" >> convert.py  # Drop only fully empty rows
            echo "df['Date'] = pd.to_datetime(df['Date'], dayfirst=True, errors='coerce')" >> convert.py
            echo "df = df[df['Date'].notna()]" >> convert.py  # Keep rows with valid dates
            echo "df = df.sort_values(by='Date')" >> convert.py
            echo "df['Date'] = df['Date'].dt.strftime('%Y-%m-%d %H:%M')" >> convert.py
            echo "print('Saving to events.json...')" >> convert.py
            echo "df.to_json('assets/data/events.json', orient='records', indent=2)" >> convert.py
            echo "print('Done.')" >> convert.py
            echo "print(df.to_string())" >> convert.py

          python convert.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull
          git add assets/data/events.json
          git commit -m "Update events.json from Google Sheets" || echo "No changes"
          git push
